### ISSUE TITLE
Replace DayJS by Luxon ?

### ISSUE THREAD

**Issue by arnauddoub** [reg2005/adonis-request-throttler#14]
Adonis users often use Luxon so there are 2 date packages installed

**Comment by VladyslavParashchenko** [comment]
Hi. Package doesn't expose dayjs details in package public interface, so I don't know any reasons why we should change date package. Maybe it will save some space on disk, but in js ecosystem node modules always taken tons of spaces.

**Comment by evoactivity** [comment]
It would be more "the adonis way" to use luxon.
