### ISSUE TITLE
How to implement adonis-request-throttler after adonis-typings change

### ISSUE THREAD

**Issue by iaamranjithkumar** [reg2005/adonis-request-throttler#6]
Hi Guys,
I am using adonis-request-throttle in our project. Thank you for this package. 
Can you tell me the new way of implementation . 

Since the export default for RequestThrottler is changed from RequestThrottlerManagerContract to Array of RequestThrottlerManagerContract in adonis-typings. This is creating repetitive loop of pushing array of RequestThrottlerManagerContract. Please find screenshot for reference.

<img width="665" alt="Screenshot 2021-07-14 at 11 08 06 AM" src="https://user-images.githubusercontent.com/36676148/125569320-797db195-99b2-4ee9-a470-578850fb2db4.png">

Was this change intentional?

Thanks,
Ranjith

**Comment by VladyslavParashchenko** [comment]
Sorry, it is only missprint. We will fix update package soon. Thx that you checked it and give us know

**Comment by MitsuhaKitsune** [comment]
This issue it's already fixed, I didn't have any problem building my adonis project with adonis-request-throttler package

**Comment by VladyslavParashchenko** [comment]
We updated package with fixed types. Thanks for using our package
