### ISSUE TITLE
Can't use current adonis-cache instance

### ISSUE THREAD

**Issue by MitsuhaKitsune** [reg2005/adonis-request-throttler#8]
Hi,

I'm using adonis-cache package on my project and it's working fine when I try to store values on cache (with cache put for example), I check my redis server database and I can see the key and value without problems.

But, when I try to disable the built-in cache on this package, didn't see any value stored on my redis database, and the throttler didn't work.

Checking the output from `RequestThrottler.verifyRequest(request)` I can see that number of attemps never up more than 1.

For now I set to true again the `useOwnCache` option and work fine, it still using my redis database and register the number of attemps without problems, but it's better if I can use my current cache instance instead init two.

As note, adonis-cache it's registered before adonis-request-throttler, so isn't missconfiguration problem I guess.

**Comment by VladyslavParashchenko** [comment]
I could reproduce this bug, but I haven't found reason yet. I will continue debug and fix it soon

**Comment by VladyslavParashchenko** [comment]
Finally, I found time for debug. You need the same `ttlUnits` in your throttler config as in cache config. By default in config examples, you will found milliseconds and minutes in this configs. Sorry, we will change default config templates.

**Comment by MitsuhaKitsune** [comment]
Yes, when I configure cache and throttler with the same ttlUnit the problem it's solved.

A lot of thanks ^^
